const ShopActionTypes = {
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  SEARCH_ITEM: "SEARCH_ITEM",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  TOGGLE_BURGER: "TOGGLE_BURGER"
};

export default ShopActionTypes;
