const CartActionTypes = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  TOGGLE_CART: 'TOGGLE_CART',
  REMOVE_ALL_FROM_AN_ITEM: 'REMOVE_ALL_FROM_AN_ITEM',
};

export default CartActionTypes;
